# Generated by Django 3.2.16 on 2023-07-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_congratulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='congratulation',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='congratulation',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
