# Generated by Django 3.2.16 on 2023-07-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230720_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Congratulation',
        ),
    ]
