# Generated by Django 3.2.16 on 2023-07-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
        ('blog', '0009_alter_post_author'),
    ]

    operations = [
    ]
