# Generated by Django 3.2.16 on 2023-07-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
